### ISSUE TITLE
Node connection endlessly loading, using own relay

### ISSUE THREAD

**Issue by realspencerdupre** [stakwork/sphinx-android#118]
The loading spinner in the upper right never stops.

Searches return nothing.

Can't tell from documentation if this is expected behavior or not with a 3rd party relay. Should I be able to load TFTC, etc.?

**Comment by realspencerdupre** [comment]
Looked at the relay server this morning. Right after the "random sig x****" line, says:
=> [meme] authed!
[hub warning]: cannot reach hub { FetchError: invalid json response body at https://hub.sphinx.chat/api/v1/ping reason: Unexpected token < in JSON at position 0
    at /home/pi/download/sphinx-relay/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://hub.sphinx.chat/api/v1/ping reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }


The URL (https://hub.sphinx.chat/api/v1/ping) shows
![Screenshot_2021-01-07_10-32-23](https://user-images.githubusercontent.com/6504771/103911142-ac104100-50d3-11eb-82b0-361f7439d876.png)

So maybe this is just a service interruption?

**Comment by realspencerdupre** [comment]
Using the Sphinx desktop version, developer tools reveals
![developer console connection error](https://user-images.githubusercontent.com/6504771/103916721-c13c9e00-50da-11eb-83eb-6165fd6d6326.png)

So now I understand. I didn't do nginx with proxy pass yet.

First I tried changing
`    "ssl": {
      "enabled": false,
      "save": true,
      "port": "80"
    }
`
into
`    "ssl": {
      "enabled": false,
      "save": true,
      "port": "8888"
    }
`

Restarted the server, wiped the desktop app account, and tried a new QR code. Still failing to connect, still using port 80.

Is a unique port supposed to be embedable in the QR code, or is always using port 80 assumed behavior?
