### ISSUE TITLE
Add step by step instructions for building (contributing)

### ISSUE THREAD

**Issue by stefan-mihaila** [stakwork/sphinx-android#22]
I am trying to build the project, but I don't know how to do it. I don't have experience with Android or React Native and I could really use some step by step instructions.

I followed the instructions from the [React Native Docs](https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment) to set up my environment. I can start the demo project `AwesomeProject` in the emulator just fine.

I'm on macOS and I have the following env variables exported:
```sh
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

This is what I currently get when I try to run `yarn android` in `sphinx-android`:
```
yarn android
yarn run v1.22.4
$ react-native run-android
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-create-bridge: https://github.com/peggyrayzis/react-native-create-bridge#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1536 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Configure project :react-native-radial-gradient
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-secure-key-store
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :rn-rncryptor
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at runOnAllDevices (/Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli/build/index.js:182:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Metro Bundler starts fine on port 8081 when running `yarn start`.

If I run `npx react-native run-android --verbose` I also get this message:
```
debug Checking manually linked modules failed., Error: ENOENT: no such file or directory, open '/Users/cypherpunk/sphinx-android/android/app/build.gradle'
```

**Comment by Evanfeenstra** [comment]
@stefan-mihaila Rename "build.copy.gradle" in android/app to simply "build.gradle". Let us know if that works (I've added that instruction to the readme as well)

**Comment by stefan-mihaila** [comment]
Thanks for the support, and sorry for bugging you with this noob stuff.

I renamed `build.copy.gradle` to `build.gradle`. Unfortunately, it still failed. Following the output.

```
yarn android
yarn run v1.22.4
$ react-native run-android
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-create-bridge: https://github.com/peggyrayzis/react-native-create-bridge#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @react-native-community/async-storage (to unlink run: "react-native unlink @react-native-community/async-storage")
  - react-native-audio-recorder-player (to unlink run: "react-native unlink react-native-audio-recorder-player")
  - react-native-camera (to unlink run: "react-native unlink react-native-camera")
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
  - react-native-get-random-values (to unlink run: "react-native unlink react-native-get-random-values")
  - react-native-haptic-feedback (to unlink run: "react-native unlink react-native-haptic-feedback")
  - react-native-image-picker (to unlink run: "react-native unlink react-native-image-picker")
  - react-native-keychain (to unlink run: "react-native unlink react-native-keychain")
  - react-native-radial-gradient (to unlink run: "react-native unlink react-native-radial-gradient")
  - react-native-randombytes (to unlink run: "react-native unlink react-native-randombytes")
  - react-native-reanimated (to unlink run: "react-native unlink react-native-reanimated")
  - react-native-rsa-native (to unlink run: "react-native unlink react-native-rsa-native")
  - react-native-safe-area-context (to unlink run: "react-native unlink react-native-safe-area-context")
  - react-native-screens (to unlink run: "react-native unlink react-native-screens")
  - react-native-secure-key-store (to unlink run: "react-native unlink react-native-secure-key-store")
  - react-native-share (to unlink run: "react-native unlink react-native-share")
  - react-native-touch-id (to unlink run: "react-native unlink react-native-touch-id")
  - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
  - react-native-webview (to unlink run: "react-native unlink react-native-webview")
  - rn-fetch-blob (to unlink run: "react-native unlink rn-fetch-blob")
  - rn-rncryptor (to unlink run: "react-native unlink rn-rncryptor")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1551 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/cypherpunk/sphinx-android/android/app/build.gradle' line: 125

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/cypherpunk/sphinx-android/android/app/build.gradle' line: 125

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at runOnAllDevices (/Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/cypherpunk/sphinx-android/node_modules/@react-native-community/cli/build/index.js:182:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

At this point if I can debug and run in the emulator is good enough, I don't need to build the apk.

**Comment by Evanfeenstra** [comment]
Hi @stefan-mihaila, can you pull the latest and try again? React-Native is a pain to get setup, but once its running its great :) Let me know if it works this time

**Comment by stefan-mihaila** [comment]
That did it @Evanfeenstra, thank you! 🎉 

Looks like I can even set breakpoints in VSCode, which is great. I'm gonna try pulling the relay and play around with it a bit.
