### ISSUE TITLE
Unable to build on Arch Linux

### ISSUE THREAD

**Issue by dmp1ce** [stakwork/sphinx-android#98]
I'm probably missing something but I wasn't able to run `npm run install-app-deps`. I was trying to build on Arch Linux using the steps in the README.md. Below is the output where I tried to install `electron-builder` and then run `install-app-deps` again.

```
david@bar:~/Workspace/sphinx-android$ npm run install-app-deps

> sphinx@0.1.0 install-app-deps /home/david/Workspace/sphinx-android
> electron-builder install-app-deps

sh: electron-builder: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sphinx@0.1.0 install-app-deps: `electron-builder install-app-deps`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the sphinx@0.1.0 install-app-deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-11-28T17_46_26_276Z-debug.log
1 david@bar:~/Workspace/sphinx-android$ npm install --save-dev electron-builder
npm notice created a lockfile as package-lock.json. You should commit this file.
+ electron-builder@22.9.1
added 190 packages from 191 contributors and audited 190 packages in 9.134s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.14.8 → 6.14.9       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.9   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

david@bar:~/Workspace/sphinx-android$ npm run install-app-deps

> sphinx@0.1.0 install-app-deps /home/david/Workspace/sphinx-android
> electron-builder install-app-deps

  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^9.2.0") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sphinx@0.1.0 install-app-deps: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sphinx@0.1.0 install-app-deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-11-28T17_47_03_805Z-debug.log
```

**Comment by pitoi** [comment]
We have a separate private repo for the linux/window version of the app. We'll do some clean up on the code and will make it public. @apocabot works on that code.

**Comment by Evanfeenstra** [comment]
@dmp1ce you were correct originally, the desktop version is in this repo as well :)

Maybe u need to install electron-builder globally? `npm i -g electron-builder`

**Comment by dmp1ce** [comment]
I tried. Here is my output.

```
david@bar:~/Workspace/sphinx-android$ npm run install-app-deps

> sphinx@0.1.0 install-app-deps /home/david/Workspace/sphinx-android
> electron-builder install-app-deps

  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^9.2.0") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sphinx@0.1.0 install-app-deps: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sphinx@0.1.0 install-app-deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-12-04T16_11_23_296Z-debug.log
1 david@bar:~/Workspace/sphinx-android$ npm i -g electron-builder
/home/david/.node_modules/bin/electron-builder -> /home/david/.node_modules/lib/node_modules/electron-builder/out/cli/cli.js
/home/david/.node_modules/bin/install-app-deps -> /home/david/.node_modules/lib/node_modules/electron-builder/out/cli/install-app-deps.js
+ electron-builder@22.9.1
added 190 packages from 191 contributors in 6.823s
david@bar:~/Workspace/sphinx-android$ npm run install-app-deps

> sphinx@0.1.0 install-app-deps /home/david/Workspace/sphinx-android
> electron-builder install-app-deps

  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^9.2.0") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sphinx@0.1.0 install-app-deps: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sphinx@0.1.0 install-app-deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-12-04T16_12_00_193Z-debug.log
1 david@bar:~/Workspace/sphinx-android$ cat ~/.npm/_logs/2020-12-04T16_12_00_193Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'install-app-deps' ]
2 info using npm@6.14.8
3 info using node@v15.3.0
4 verbose run-script [ 'preinstall-app-deps', 'install-app-deps', 'postinstall-app-deps' ]
5 info lifecycle sphinx@0.1.0~preinstall-app-deps: sphinx@0.1.0
6 info lifecycle sphinx@0.1.0~install-app-deps: sphinx@0.1.0
7 verbose lifecycle sphinx@0.1.0~install-app-deps: unsafe-perm in lifecycle true
8 verbose lifecycle sphinx@0.1.0~install-app-deps: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/david/Workspace/sphinx-android/node_modules/.bin:/home/david/.local/bin:/home/david/.node_modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
9 verbose lifecycle sphinx@0.1.0~install-app-deps: CWD: /home/david/Workspace/sphinx-android
10 silly lifecycle sphinx@0.1.0~install-app-deps: Args: [ '-c', 'electron-builder install-app-deps' ]
11 silly lifecycle sphinx@0.1.0~install-app-deps: Returned: code: 1  signal: null
12 info lifecycle sphinx@0.1.0~install-app-deps: Failed to exec install-app-deps script
13 verbose stack Error: sphinx@0.1.0 install-app-deps: `electron-builder install-app-deps`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:376:20)
13 verbose stack     at maybeClose (node:internal/child_process:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
14 verbose pkgid sphinx@0.1.0
15 verbose cwd /home/david/Workspace/sphinx-android
16 verbose Linux 5.4.80-2-lts
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "install-app-deps"
18 verbose node v15.3.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error sphinx@0.1.0 install-app-deps: `electron-builder install-app-deps`
22 error Exit status 1
23 error Failed at the sphinx@0.1.0 install-app-deps script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by dmp1ce** [comment]
I had gotten it to build in the past. This issue is old. Closing.
